In [4]:
import pandas as pd

In [5]:
data=pd.read_csv("mtcars.csv")
data['carb'].nunique()
data

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [6]:
data.isnull().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

# Make feature & target columns

In [100]:
x=data[["mpg","cyl","disp"]].values
y=data["carb"].values

# feature scalling using standardtization

In [101]:
from sklearn.preprocessing import StandardScaler # 
dt=StandardScaler().fit_transform(x)
#dt.fit_transform(x)

In [102]:
print(dt.max())
print(dt.min())

2.3279342893096193
-1.6336103713847328

#  feature scalling using Normalization

In [111]:
from sklearn.preprocessing import MinMaxScaler
dt=MinMaxScaler(feature_range=(1,2)).fit_transform(x)
dt

array([[1.45106383, 1.5       , 1.22175106],
       [1.45106383, 1.5       , 1.22175106],
       [1.52765957, 1.        , 1.0920429 ],
       [1.46808511, 1.5       , 1.46620105],
       [1.35319149, 2.        , 1.72062859],
       [1.32765957, 1.5       , 1.38388626],
       [1.16595745, 2.        , 1.72062859],
       [1.59574468, 1.        , 1.1885757 ],
       [1.52765957, 1.        , 1.17385882],
       [1.37446809, 1.5       , 1.24070841],
       [1.31489362, 1.5       , 1.24070841],
       [1.25531915, 2.        , 1.51060115],
       [1.29361702, 2.        , 1.51060115],
       [1.20425532, 2.        , 1.51060115],
       [1.        , 2.        , 2.        ],
       [1.        , 2.        , 1.97006735],
       [1.18297872, 2.        , 1.9201796 ],
       [1.93617021, 1.        , 1.01895735],
       [1.85106383, 1.        , 1.01147418],
       [2.        , 1.        , 1.        ],
       [1.47234043, 1.        , 1.12222499],
       [1.21702128, 2.        , 1.61586431],
       [1.20425532, 2.        , 1.58094288],
       [1.12340426, 2.        , 1.69568471],
       [1.37446809, 2.        , 1.82040409],
       [1.71914894, 1.        , 1.01970566],
       [1.66382979, 1.        , 1.12272387],
       [1.85106383, 1.        , 1.0598653 ],
       [1.22978723, 2.        , 1.6981791 ],
       [1.39574468, 1.5       , 1.18433525],
       [1.19574468, 2.        , 1.57345972],
       [1.46808511, 1.        , 1.12446994]])

In [104]:
print(dt.max())
print(dt.min())

2.0
1.0

# Splitting & Shuffel data

In [119]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(dt,y,test_size=0.2,random_state=10)

In [121]:
x_train.shape

(25, 3)

In [122]:
x_test.shape

(7, 3)

In [125]:
y_test.shape

(7,)

In [118]:
x_test.shape

(7, 3)

# Import KNN classifier & apply

In [126]:
from sklearn.neighbors import KNeighborsClassifier

In [128]:
knn=KNeighborsClassifier(metric='euclidean',p=2)

In [129]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [132]:
pred=knn.predict(x_test)

# Cross check accuracy

In [133]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import classification
from sklearn.metrics import precision_score
from skleran.metrics import

In [147]:
#print("Accuracy score- -{}".format(accuracy_score(pred,y_test)))
#print("confusion_matrix- -{}".format(confusion_matrix(pred,y_test)))
#f1_score(pred,y_test)
print("classification_report- -{}".format(classification_report(pred,y_test)))
#print("precision_score- -{}".format(precision_score(pred,y_test)))

classification_report- -              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       0.50      0.33      0.40         3
           3       1.00      1.00      1.00         1
           4       0.00      0.00      0.00         3

    accuracy                           0.29         7
   macro avg       0.38      0.33      0.35         7
weighted avg       0.36      0.29      0.31         7

In [140]:
y_test

array([1, 2, 1, 1, 1, 2, 3], dtype=int64)

In [148]:
pred

array([2, 2, 4, 2, 4, 4, 3], dtype=int64)

# Feature selection

In [1]:
import seaborn as sb
sb.pairplot(data,hue="carb")

NameError: name 'data' is not defined

In [9]:
data

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2